server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
spring:
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: jdbc:mysql://localhost:3306/laborator8PA
    username: root
    password: valeriacotruta
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true